

#define ROBOT_ARUCO_ID 188
#define OVERHEAD_CAMERA_CHANNEL 1
#define FRAME_GETTER_TIMEOUT_MS 20

#define OVERHEAD_CAMERA_CHANNEL 1
#define ARENA_WIDTH 1.6383f
#define ARENA_HEIGHT 1.6383f

#define ARUCO_TAG_CAMERA 24
#define ARUCO_TAG_PKG1 5
#define ARUCO_TAG_PKG2 6
#define ARUCO_TAG_TRK1 1
#define ARUCO_TAG_TRK2 2
#define ARUCO_TAG_TRK3 3
#define ARUCO_TAG_TRK4 4


//
#define MOTOR_L1 17
#define MOTOR_L2 4
#define MOTOR_R1 22
#define MOTOR_R2 27

#define FORKLIFT_SERVO 14

#define LEFT_MOTOR_SPEED_OFFSET 0
#define RIGHT_MOTOR_SPEED_OFFSET 0

#define TOP_SPEED_PWM 255
#define SLOW_SPEED_PWM 150

#define RMOTORDRIVER_JOYSTICK_CENTER 50.0f
#define RMOTORDRIVER_DEADZONE 3.0f       // Deadzone around center
#define RMOTORDRIVER_MAX_INPUT 50.0f     // Joystick value range from center
#define RMOTORDRIVER_MAX_OUTPUT 255.0f   // Max motor speed

#define SERVER_PORT 5008

#define SERVER_TX_REQ "REQ E4699FMK1\n"
#define SERVER_RX_ACK "ACK MK1FE4699\n"

#define CAMERA_CALIBRATION "./calibration.yaml"